### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by MishraSomesh001** [OPCODE-Open-Spring-Fest/auction#1]
### Add NFT Contract Reference:
- Add a reference to the ERC721 contract for the NFTs being auctioned.

### Bid Placement with NFT:
- Modifie the `placeBid` function to accept an additional parameter `_tokenId` representing the NFT token ID.
- Bidders must send the NFT token they want to bid with as part of the bid.
- Add a check to ensure that the bidder owns the NFT they are bidding with.

### Finalizing the Auction:
- Modifie the `finalizeAuc` function to transfer the NFT to the highest bidder if the auction is not cancelled.
- Use the `safeTransferFrom` function from the ERC721 contract to transfer the NFT securely.

### Implemente ERC721 Receiver:
- Implemente the `onERC721Received` function as required by the `IERC721Receiver` interface.
- This function allows the contract to receive NFTs when they are transferred to it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001 Can I have this assignment

**Comment by Jagpreet153** [comment]
@MishraSomesh001 Please assign this task to me

**Comment by MishraSomesh001** [comment]
##Assigned
You have to submit one pr before 17-04-24,12pm.
