### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by MishraSomesh001** [OPCODE-Open-Spring-Fest/auction#2]
### Event: BidPlaced
- Add an event `BidPlaced` to emit when a bid is placed.
- This allows external systems to listen for bid placements and track auction activity.

### Withdraw Function:
- Add a `withdraw` function that allows bidders to withdraw their bids if the auction is cancelled.
- Bidders can call this function to retrieve their bid amount if the auction is cancelled or they are not the highest bidder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001 Please assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
@xTwo56 you have to submit a pr before 2-04-24, 11:59pm
